todo/urls.py
from django.urls import path

from todo import views

urlpatterns = [
    path('', views.TodoList.as_view(), name='todo-list'),
    path('api/all/', views.TodoListAPI.as_view(), name='todo-list-api'),
    path('<int:pk>/', views.TodoDetailView.as_view(), name='todo-detail'),
    path('api/<int:pk>/', views.TodoDetailAPI.as_view(), name='todo-detail-api'),
    path('add_todo/', views.TodoCreateView.as_view(), name='todo-create'),
    path('edit_todo/<int:pk>/', views.TodoUpdate.as_view(), name='todo-update'),
    path('delete_todo/<int:pk>/', views.TodoDelete.as_view(), name='todo-delete'),
]

todo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/models.py
from django.db import models
from django.urls import reverse


class Todo(models.Model):
    """Model for todo app."""
    PENDING = 'PENDING'
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'
    STATUS_CHOICES = (
        (1, PENDING),
        (2, IN_PROGRESS),
        (3, COMPLETED),
    )
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    task_time = models.DateTimeField(null=True, blank=True)
    status = models.PositiveSmallIntegerField(default=1, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('todo-detail', kwargs={'pk': self.pk})

todo/views.py
from django.core import serializers
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from todo.models import Todo


class TodoList(ListView):
    """List all the active todos."""

    def get_queryset(self):
        return Todo.objects.filter(is_active=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Todo Home'
        context['current'] = 'List'
        return context


class TodoListAPI(TodoList):
    """API for List all the actives todos."""
    def get(self, request):
        response = self.get_queryset()
        return JsonResponse(serializers.serialize('json', response), safe=False)


class TodoDetailView(DetailView):
    """List particular todo."""
    model = Todo

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Todo'
        return context


class TodoDetailAPI(TodoDetailView):
    """API to list particular todo."""

    def get(self, *args,  **kwargs):
        response = self.get_queryset().filter(pk=self.kwargs['pk'])
        return JsonResponse(serializers.serialize('json', response), safe=False)


class TodoCreateView(CreateView):
    """Create a new todo task."""
    model = Todo
    fields = ['title', 'description', 'task_time', 'status']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add Todo Task'
        context['current'] = 'Create'
        return context


class TodoUpdate(TodoDetailView, UpdateView):
    """Update an existing todo."""
    model = Todo
    fields = ['title', 'description', 'task_time', 'status']
    template_name_suffix = '_update_form'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit Todo Task'
        return context


class TodoDelete(DeleteView):
    """Soft delete an existing todo."""
    model = Todo
    success_url = reverse_lazy('todo-list')

    def delete(self, request, *args, **kwargs):
        """Soft Delete.

        Set is_active to False of the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Delete Todo Task'
        return context

todo/templates/todo/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">

    <title>{% block title %}{{ section.title }}{% endblock %}</title>
  </head>
  <body>
    {% include "todo/nav_bar.html" %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.min.js" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    {% block externaljs %}
    {% endblock %}
  </body>
</html>

todo/templates/todo/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'todo-list' %}">Todo App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link {% if current == 'Create' %} active {% endif %}" href="{% url 'todo-create' %}">Add Task {% if current == 'Create' %}<span class="sr-only">(current)</span>{% endif %} </a>
    </div>
  </div>
</nav>

todo/templates/todo/todo_confirm_delete.html
{% extends "todo/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="col-offset-3 mt-5">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" class="btn btn-danger" value="Confirm">
        </form>
    </div>
{% endblock %}

todo/templates/todo/todo_detail.html
{% extends "todo/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="col-offset-3 mt-5">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ object.title|title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ object.get_status_display }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">{{ object.task_time }}</h6>
            <p class="card-text">{{ object.description }}</p>
            <a href="{% url 'todo-update' object.pk %}" class="card-link">Edit</a>
            <a href="{% url 'todo-delete' object.pk %}" class="card-link text-danger">Delete</a>
          </div>
        </div>
    </div>
{% endblock %}

todo/templates/todo/todo_form.html
{% extends "todo/base.html" %}
{% load widget_tweaks %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1>Add a Task</h1>
<form method="post">{% csrf_token %}

    {% for field in form.visible_fields %}
    <div class="form-group" style="position: relative;">
        {{ field.label_tag }}
        {% render_field field class="form-control" %}
        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Add Task</button>
</form>
{% endblock %}
{% block externaljs %}
<script type="text/javascript">
    $(function () {
        $('#id_task_time').datetimepicker({
            format: 'YYYY-MM-DD h:mm:ss'
        });
    });
</script>
{% endblock %}

todo/templates/todo/todo_list.html
{% extends "todo/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="col-offset-3 mt-5">
    <h1>Your Todo...</h1>
    <div class="card">
        <ul class="list-group list-group-flush">
            {% for todo in object_list %}
            <li class="list-group-item"><a href="{% url 'todo-detail' todo.pk %}">{{ todo.title }}</a></li>
            {% empty %}
                <li>No Todo items yet.</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

todo/templates/todo/todo_update_form.html
{% extends "todo/base.html" %}
{% load widget_tweaks %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1>Edit the Task</h1>
<form method="post">{% csrf_token %}

    {% for field in form.visible_fields %}
    <div class="form-group" style="position: relative;" >
        {{ field.label_tag }}
        {% render_field field class="form-control" %}
        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Update</button>
</form>
{% endblock %}
{% block externaljs %}
<script type="text/javascript">
    $(function () {
        $('#id_task_time').datetimepicker({
            format: 'YYYY-MM-DD h:mm:ss'
        });
    });
</script>
{% endblock %}